name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASS: ${{secrets.PASS}}

        
      run: |        
        docker build . --file Dockerfile --tag krushnapatel7/devops-ci-demo-2026:v1
        docker login -u $USERNAME -p $PASS        
        docker push krushnapatel7/devops-ci-demo-2026:v1
